export const unitFullNames: Record<string, string> = {
  // --- Length ---
  m: "Meters",
  km: "Kilometers",
  cm: "Centimeters",
  mm: "Millimeters",
  µm: "Micrometers",
  nm: "Nanometers",
  pm: "Picometers",
  fm: "Femtometers",
  am: "Attometers",
  zm: "Zeptometers",
  ym: "Yoctometers",
  mi: "Miles",
  yd: "Yards",
  ft: "Feet",
  in: "Inches",
  nmi: "Nautical Miles",
  angstrom: "Angstroms",
  au: "Astronomical Units",
  ly: "Light Years",
  pc: "Parsecs",

  // --- Mass ---
  kg: "Kilograms",
  g: "Grams",
  mg: "Milligrams",
  µg: "Micrograms",
  ng: "Nanograms",
  lb: "Pounds",
  oz: "Ounces",
  ton: "Tons (Imperial)",
  tonne: "Tonnes (Metric)",
  slug: "Slugs",
  stone: "Stones",

  // --- Time ---
  s: "Seconds",
  ms: "Milliseconds",
  µs: "Microseconds",
  ns: "Nanoseconds",
  ps: "Picoseconds",
  min: "Minutes",
  h: "Hours",
  day: "Days",
  week: "Weeks",
  month: "Months (30 days)",
  year: "Years (365 days)",
  fortnight: "Fortnights",

  // --- Temperature ---
  K: "Kelvin",
  degC: "Degrees Celsius",
  degF: "Degrees Fahrenheit",
  degR: "Degrees Rankine",

  // --- Volume ---
  "m³": "Cubic Meters",
  "cm³": "Cubic Centimeters",
  "mm³": "Cubic Millimeters",
  l: "Liters",
  ml: "Milliliters",
  gal: "Gallons (US)",
  qt: "Quarts (US)",
  pt: "Pints (US)",
  cup: "Cups (US)",
  floz: "Fluid Ounces (US)",
  tbsp: "Tablespoons (US)",
  tsp: "Teaspoons (US)",

  // --- Area ---
  "m²": "Square Meters",
  "km²": "Square Kilometers",
  "cm²": "Square Centimeters",
  "mm²": "Square Millimeters",
  ha: "Hectares",
  acre: "Acres",
  "ft²": "Square Feet",
  "in²": "Square Inches",
  "mi²": "Square Miles",

  // --- Speed ---
  "m/s": "Meters per Second",
  "km/h": "Kilometers per Hour",
  mph: "Miles per Hour",
  knot: "Knots",

  // --- Acceleration ---
  "m/s²": "Meters per Second Squared",

  // --- Force ---
  N: "Newtons",
  lbf: "Pound-Force",
  dyn: "Dynes",

  // --- Energy ---
  J: "Joules",
  kJ: "Kilojoules",
  cal: "Calories",
  kcal: "Kilocalories",
  Wh: "Watt Hours",
  kWh: "Kilowatt Hours",
  BTU: "British Thermal Units",
  erg: "Ergs",
  eV: "Electronvolts",

  // --- Power ---
  W: "Watts",
  kW: "Kilowatts",
  MW: "Megawatts",
  GW: "Gigawatts",
  hp: "Horsepower",

  // --- Pressure ---
  Pa: "Pascals",
  kPa: "Kilopascals",
  bar: "Bar",
  atm: "Atmospheres",
  psi: "Pounds per Square Inch",
  torr: "Torr",
  mmHg: "Millimeters of Mercury",

  // --- Frequency ---
  Hz: "Hertz",
  kHz: "Kilohertz",
  MHz: "Megahertz",
  GHz: "Gigahertz",
  THz: "Terahertz",

  // --- Electric ---
  V: "Volts",
  A: "Amperes",
  C: "Coulombs",
  Ω: "Ohms",
  F: "Farads",
  S: "Siemens",
  H: "Henries",
  Wb: "Webers",
  T: "Teslas",
  lx: "Lux",

  // --- Angle & Rotation ---
  rad: "Radians",
  deg: "Degrees",
  grad: "Gradians",
  cycle: "Cycles",
  turn: "Turns",
  rev: "Revolutions",

  // --- Charge & Capacitance ---
  e: "Elementary Charges",

  // --- Magnetic & Light ---
  lm: "Lumens",
  ph: "Photons",

  // --- Miscellaneous / Dimensionless ---
  "%": "Percent",
  ppm: "Parts per Million",
  ppb: "Parts per Billion",
  pptr: "Parts per Trillion",
  dB: "Decibels",
  bit: "Bits",
  byte: "Bytes",

  // --- Digital Storage ---
  b: "Bits",
  B: "Bytes",
  kb: "Kilobits",
  kB: "Kilobytes",
  Mb: "Megabits",
  MB: "Megabytes",
  Gb: "Gigabits",
  GB: "Gigabytes",
  Tb: "Terabits",
  TB: "Terabytes",

  // --- Currency ---
  USD: "US Dollars",
  EUR: "Euros", 
  GBP: "British Pounds",
  AUD: "Australian Dollars",
  CAD: "Canadian Dollars",
  CHF: "Swiss Francs",
  JPY: "Japanese Yen",
  CNY: "Chinese Yuan",
  INR: "Indian Rupees",
  NZD: "New Zealand Dollars",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  SGD: "Singapore Dollars",
  HKD: "Hong Kong Dollars",
  KRW: "South Korean Won",
  MXN: "Mexican Peso",
  BRL: "Brazilian Real",
  RUB: "Russian Ruble", 
  TRY: "Turkish Lira",
  ZAR: "South African Rand",
  PLN: "Polish Zloty",
  THB: "Thai Baht",
  DKK: "Danish Krone",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  ILS: "Israeli Shekel",
  PHP: "Philippine Peso",
  TWD: "Taiwan Dollar",
  MYR: "Malaysian Ringgit",
  
  // --- Cryptocurrencies ---
  BTC: "Bitcoin",
  ETH: "Ethereum",
  XRP: "Ripple",
  LTC: "Litecoin",
  ADA: "Cardano",
  DOT: "Polkadot",
  SOL: "Solana",
  MATIC: "Polygon",
  AVAX: "Avalanche",
  UNI: "Uniswap",
};
